

set_property IOSTANDARD LVCMOS18 [get_ports sum_0]
set_property IOSTANDARD LVCMOS18 [get_ports carry_0]
set_property PACKAGE_PIN AR13 [get_ports carry_0]
set_property PACKAGE_PIN AP13 [get_ports sum_0]
set_property PACKAGE_PIN AW3 [get_ports a_0]
set_property IOSTANDARD LVCMOS18 [get_ports a_0]
set_property PACKAGE_PIN AW6 [get_ports b_0]
set_property IOSTANDARD LVCMOS18 [get_ports b_0]
set_property IOSTANDARD LVCMOS18 [get_ports c_0]
set_property PACKAGE_PIN AM15 [get_ports default_sysclk3_100mhz_clk_p]
set_property PACKAGE_PIN AW5 [get_ports c_0]
connect_debug_port dbg_hub/clk [get_nets clk]

set_property PACKAGE_PIN AM15 [get_ports clk_0]
set_property IOSTANDARD LVDS [get_ports clk_0]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_0_IBUF]
