create_clock -period 10.000 -name clk_in1_0 [get_ports clk_in1_0]

set_property PACKAGE_PIN AR13 [get_ports {dataout_0[3]}]
set_property PACKAGE_PIN AP13 [get_ports {dataout_0[2]}]
set_property PACKAGE_PIN AR16 [get_ports {dataout_0[1]}]
set_property PACKAGE_PIN AP16 [get_ports {dataout_0[0]}]
set_property PACKAGE_PIN AN16 [get_ports lastout_0]
set_property PACKAGE_PIN AN17 [get_ports validout_0]
set_property PACKAGE_PIN J19 [get_ports clk_in1_0]
set_property IOSTANDARD LVCMOS18 [get_ports resetn_0]
set_property IOSTANDARD LVCMOS18 [get_ports {dataout_0[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dataout_0[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dataout_0[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dataout_0[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports lastout_0]
set_property IOSTANDARD LVCMOS18 [get_ports validout_0]
set_property IOSTANDARD LVDS [get_ports clk_in1_0]

set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
